services:
  vps-test:
    image: ubuntu:latest
    container_name: vps-setup-test
    tty: true
    stdin_open: true
    environment:
      - DEBIAN_FRONTEND=noninteractive
      - SSH_ADMIN_IPS=${SSH_ADMIN_IPS:-}
    volumes:
      - ./test-data:/mnt/data
    command: >
      bash -c "apt-get update && \
      apt-get install ca-certificates -y && \
      apt-get install -y --no-install-recommends curl sudo ufw && \
      apt-get clean && rm -rf /var/lib/apt/lists/* && \
      curl -fsSL https://raw.githubusercontent.com/BCars-SA/knowledge/main/vps/setup-ubuntu/setup-vps.sh -o /root/setup-vps.sh && \
      sudo chmod +x /root/setup-vps.sh && \
      /root/setup-vps.sh || bash"